### PR TITLE
Fix dependencies

### PR DESCRIPTION
**Pull request by otaviopace**
This Pull Request does two things:

- Updates `package-lock.json`;
- Uses `idempotent-babel-polyfill` so that if other programs/libraries import `sqs-quooler` they won't get in to the error: `only one instance of babel-polyfill is allowed`. To read more about it: https://github.com/babel/babel-loader/issues/401.

### CODE REVIEW

**Comment by claytonsilva** [comment]
@ahmarcia @jeanaugustoos @lucianopf tem algo que impede de criarmos uma release? posso mandar ver e fechar essa pr?

**Comment by lucianopf** [comment]
Nada, bora fazer! ❤️

**Comment by lucianopf** [comment]
Feito!! https://www.npmjs.com/package/sqs-quooler/v/1.6.0

Brigadão por puxar o assunto dnv @claytonsilva !!

**Comment by otaviopace** [comment]
Muito obrigado galera ❤️

**Pull request merged**
